export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      service_requests: {
        Row: {
          id: string;
          request_source: string | null;
          salutation: string | null;
          first_name: string | null;
          last_name: string | null;
          name: string;
          phone: string;
          email: string | null;
          location: string | null;
          service_type: string;
          service_category: string | null;
          selected_services: Json | null;
          effort_size: string | null;
          distance_zone: string | null;
          description: string | null;
          desired_date: string | null;
          price_type: string | null;
          estimated_price: string | null;
          fixed_price_suggestion: string | null;
          calculator_data: Json | null;
          status: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          request_source?: string | null;
          salutation?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          name: string;
          phone: string;
          email?: string | null;
          location?: string | null;
          service_type: string;
          service_category?: string | null;
          selected_services?: Json | null;
          effort_size?: string | null;
          distance_zone?: string | null;
          description?: string | null;
          desired_date?: string | null;
          price_type?: string | null;
          estimated_price?: string | null;
          fixed_price_suggestion?: string | null;
          calculator_data?: Json | null;
          status?: string | null;
          created_at?: string | null;
        };
        Update: {
          request_source?: string | null;
          salutation?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          name?: string;
          phone?: string;
          email?: string | null;
          location?: string | null;
          service_type?: string;
          service_category?: string | null;
          selected_services?: Json | null;
          effort_size?: string | null;
          distance_zone?: string | null;
          description?: string | null;
          desired_date?: string | null;
          price_type?: string | null;
          estimated_price?: string | null;
          fixed_price_suggestion?: string | null;
          calculator_data?: Json | null;
          status?: string | null;
        };
        Relationships: [];
      };
      request_images: {
        Row: {
          id: string;
          request_id: string | null;
          file_url: string;
          file_name: string | null;
          file_type: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          request_id?: string | null;
          file_url: string;
          file_name?: string | null;
          file_type?: string | null;
          created_at?: string | null;
        };
        Update: {
          request_id?: string | null;
          file_url?: string;
          file_name?: string | null;
          file_type?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      offers: {
        Row: {
          id: string;
          customer_key: string | null;
          request_id: string | null;
          offer_number: string | null;
          salutation: string | null;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          service_category: string | null;
          service_description: string | null;
          execution_location: string | null;
          planned_date: string | null;
          valid_until: string | null;
          net_price: number | null;
          discount_percent: number | null;
          special_price: number | null;
          material_costs: number | null;
          travel_costs: number | null;
          disposal_costs: number | null;
          other_costs: number | null;
          vat_rate: number | null;
          gross_total: number | null;
          payment_type: string | null;
          legal_notes: string | null;
          status: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          customer_key?: string | null;
          request_id?: string | null;
          offer_number?: string | null;
          salutation?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          service_category?: string | null;
          service_description?: string | null;
          execution_location?: string | null;
          planned_date?: string | null;
          valid_until?: string | null;
          net_price?: number | null;
          discount_percent?: number | null;
          special_price?: number | null;
          material_costs?: number | null;
          travel_costs?: number | null;
          disposal_costs?: number | null;
          other_costs?: number | null;
          vat_rate?: number | null;
          gross_total?: number | null;
          payment_type?: string | null;
          legal_notes?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Update: {
          customer_key?: string | null;
          request_id?: string | null;
          offer_number?: string | null;
          salutation?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          service_category?: string | null;
          service_description?: string | null;
          execution_location?: string | null;
          planned_date?: string | null;
          valid_until?: string | null;
          net_price?: number | null;
          discount_percent?: number | null;
          special_price?: number | null;
          material_costs?: number | null;
          travel_costs?: number | null;
          disposal_costs?: number | null;
          other_costs?: number | null;
          vat_rate?: number | null;
          gross_total?: number | null;
          payment_type?: string | null;
          legal_notes?: string | null;
          status?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
